<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dd_sim">
    
    <!--Parameters-->
    <xacro:property name="base_width" value="0.16"/>
    <xacro:property name="base_length" value="0.16"/>
    <xacro:property name="base_height" value="0.03"/>
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.015"/>
    <xacro:property name="wheel_separation" value="0.15"/>
    <xacro:property name="base_wheel_gap" value="0.007"/>
    <xacro:property name="wheel_offset" value="0.02"/>
    <xacro:property name="ball_radius" value="${wheel_radius/2}"/>
    <xacro:property name="ball_offset" value="-0.052"/>
    
    <xacro:property name="link_01_radius" value="0.05"/>
    <xacro:property name="link_01_length" value="0.02"/>
    <xacro:property name="link_02_radius" value="0.03"/>
    <xacro:property name="link_02_length" value="0.08"/>
    <xacro:property name="link_03_radius" value="0.03"/>
    <xacro:property name="link_03_length" value="0.12"/>
    <xacro:property name="link_04_radius" value="0.03"/>
    <xacro:property name="link_04_length" value="0.08"/>

    <!--Color Properties-->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name = "orange">
		<color rgba ="0.8 0.4 0.0 1.0"/>
	</material>
    <material name = "green">
		<color rgba ="0 0.8 0.0 1.0"/>
	</material>
    <material name = "purple">
		<color rgba ="0.8 0 0.4 1.0"/>
	</material>

    <!--Interial macros-->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
        <mass value="${m}"/>
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
        <mass value="${m}"/>
        <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
        <mass value="${m}"/>
        <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
        </inertial>
    </xacro:macro>

    <!-- add color to gazebo-->
    <gazebo reference = "base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference = "left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference = "right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    
    <gazebo reference = "ball_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference = "link_01">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference = "link_02">
        <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference = "link_03">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference = "link_04">
        <material>Gazebo/Purple</material>
    </gazebo>

    <!--foorprint-->
    <link name = "footprint">
        <xacro:box_inertia m="10" w="0.001" h="0.001" d = "0.001"/>
        <visual>
            <origin xyz = "0 0 0 " rpy = "0 0 0 "/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>
    
    <!--Base Link-->
    <link name="base_link">
        <xacro:box_inertia m="3" w="${base_length}" h="${base_width}" d="${base_height}"/>
        <visual>
          <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
          </geometry>
          <!--origin rpy="0 0 0" xyz="0 0 ${(base_height/2)+(2*ball_radius)}"/-->
          <material name="orange"/>
        </visual>
        <collision>
          <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
          </geometry>
          <!--origin rpy="0 0 0" xyz="0 0 ${(base_height/2)+(2*ball_radius)}"/-->
        </collision>
    </link>

    <!--base link to footprint-->
    <joint name = "base_link_footprint" type="fixed">
        <origin xyz = "0 0 ${wheel_radius + wheel_length}" rpy = "0 0 0"/>
        <parent link = "footprint"/>
        <child link="base_link"/>
    </joint>

    <!--Wheel link & joint macro-->
    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_length}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${wheel_offset} ${(base_width/2+base_wheel_gap)*reflect} -${wheel_length}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!--Create Left & Right Wheel links/joints-->
    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>

    <!--ball Wheel Link-->
    <link name="ball_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${ball_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${ball_radius}"/>
        </geometry>
        </collision>
        <xacro:sphere_inertia m="1" r="${ball_radius}"/>
    </link>

    <!--Ball Wheel Joint-->
    <joint name="ball_wheel_joint" type="continuous">
        <axis xyz="0 1 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="ball_wheel"/>
        <origin xyz="${ball_offset} 0 -${ball_radius+wheel_length}" rpy="0 0 0"/>
    </joint>

    <!-- manipulator-->
    <link name="link_01">
        <visual>
            <origin rpy = "0 0 0 " xyz = "0 0 ${link_01_length/2}"/>
            <geometry>
                <cylinder radius="${link_01_radius}" length="${link_01_length}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${link_01_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_01_radius}" length="${link_01_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${link_01_radius}" h="${link_01_length}"/>
    </link>

    <joint name="base_link_to_link_01" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort = "100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
        <origin rpy = "0 0 0 " xyz = "0 0 ${base_height/2}"/>
        <parent link = "base_link"/>
        <child link = "link_01"/>
    </joint>

    <transmission name="trans_base_link_to_link_01">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name = "base_link_to_link_01">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_base_link_to_link_01">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <link name="link_02">
        <visual>
            <origin rpy = "0 0 0 " xyz = "0 0 ${link_02_length/2}"/>
            <geometry>
                <cylinder radius="${link_02_radius}" length="${link_02_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${link_02_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_02_radius}" length="${link_02_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${link_02_radius}" h="${link_02_length}"/>
    </link>

    <joint name="link_01_to_link_02" type="revolute">
        <axis xyz="0 1 0"/>
        <limit effort = "100.0" lower="-1.57" upper="1.57" velocity="0.5"/>
        <origin rpy = "0 0 0 " xyz = "0 0 ${link_01_length}"/>
        <parent link = "link_01"/>
        <child link = "link_02"/>
    </joint> 

    <transmission name="trans_link_01_to_link_02">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name = "link_01_to_link_02">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_01_to_link_02">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    
    <!--link name="link_03">
        <visual>
            <origin rpy = "0 0 0 " xyz = "0 0 ${link_03_length/2}"/>
            <geometry>
                <cylinder radius="${link_03_radius}" length="${link_03_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${link_03_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_03_radius}" length="${link_03_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${link_03_radius}" h="${link_03_length}"/>
    </link>

    <joint name="link_02_to_link_03" type="revolute">
        <axis xyz="0 1 0"/>
        <limit effort = "100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
        <origin rpy = "0 0 0 " xyz = "0 0 ${link_02_length}"/>
        <parent link = "link_02"/>
        <child link = "link_03"/>
    </joint> 

    <transmission name="trans_link_02_to_link_03">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name = "link_02_to_link_03">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_02_to_link_03">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission-->

    <!--link name="link_04">
        <visual>
            <origin rpy = "0 0 0 " xyz = "0 0 ${link_04_length/2}"/>
            <geometry>
                <cylinder radius="${link_04_radius}" length="${link_04_length}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${link_04_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_04_radius}" length="${link_04_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="${link_04_radius}" h="${link_04_length}"/>
    </link>

    <joint name="link_03_to_link_04" type="revolute">
        <axis xyz="0 1 0"/>
        <limit effort = "100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
        <origin rpy = "0 0 0 " xyz = "0 0 ${link_03_length}"/>
        <parent link = "link_03"/>
        <child link = "link_04"/>
    </joint> 

    <transmission name="trans_link_03_to_link_04">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name = "link_03_to_link_04">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_link_03_to_link_04">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission-->

    <xacro:include filename="$(find dd_sim)/urdf/dd_gazebo_plugins.xacro"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        </plugin>
    </gazebo>

</robot>