dd:  
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_01_to_link_02
    pid: {p: 100.0, i: 0.001, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_02_to_link_03
    pid: {p: 100.0, i: 0.001, d: 10.0}

